FROM node:8

RUN apt-get update &&  apt-get install git

ADD lib/helper.js kubeless_rt/lib/
ADD kubeless.js kubeless_rt/
ADD package.json kubeless_rt/

WORKDIR kubeless_rt/

RUN npm install

USER 1000

ENTRYPOINT echo cleanup; for i in $(env | grep '_SERVICE_\|_PORT' | cut -f1 -d=); do unset $i; done; echo '---'; echo $(env); node kubeless.js
